### PR TITLE
Multi dim

### PR DESCRIPTION
**Pull request by Vayel**
See #119 and #122

### CODE REVIEW

**Comment by Vayel** [comment]
@MaxHalford I think I'm done here. If you merge, can you merge the other PRs before?

**Comment by MaxHalford** [comment]
@Vayel is this working now?

**Comment by Vayel** [comment]
If the tests pass, yes.

**Comment by MaxHalford** [comment]
Ah yes my bad, I didn't see your previous comment! I'll check and merge the other PRs :)

**Comment by Vayel** [comment]
@MaxHalford ok for you?

**Pull request merged**
